#  Spencer Yoder
#    Z1814808
#    CSCI 340-2
#
#    I certify that this is my own work and where appropriate an extension
#    of the starter code provided for the assignment.


assignment00.exe: assignment00.cc
	g++ -Wall -o assignments00.exe assignment00.cc

