#  Spencer Yoder
#    Z1814808
#    CSCI 340-2
#
#    I certify that this is my own work and where appropriate an extension
#    of the starter code provided for the assignment.

assignment02.exe: assignment02.cc
	g++ -std=c++11 -Wall -o assignments02.exe assignment02.cc
